### ISSUE TITLE
No 1.21 enchantments in Variants-CIT version of Even Better Enchants

### ISSUE THREAD

**Issue by RomanPro100** [Estecka/mc-Enchants-CIT#12]
3 new enchantments were added to Minecraft 1.21 (Breach, Density, Wind Burst) and they're already present in the [original Even Better Enchants resourcepack](https://modrinth.com/resourcepack/even-better-enchants), but not in the Variants-CIT version.
I made my own version until it gets released in this repo:
[Even-Better-Enchants_Variants-CIT.zip](https://github.com/user-attachments/files/17003014/Even-Better-Enchants_Variants-CIT.zip)

**Comment by Estecka** [comment]
Thanks, although I just published an updated version a few hours ago (probably around the same time as you did lol).

The link on the modrinth page is updated; the pack is available as an additional file under the v2.4 version of Variants-CIT.

**Comment by Estecka** [comment]
P.S: In that version, I removed the model files and kept only the textures, so it will need at least v2.4 in order to work.
