### ISSUE TITLE
Enchanted Pulling Bow Texture

### ISSUE THREAD

**Issue by cramoraint** [Estecka/mc-Enchants-CIT#17]
Is it possible to change the pulling bow texture when it is enchanted with the flame enchantment? I am unsure how to do this.

**Comment by Estecka** [comment]
That should be possible. In addition to the textures, you'll need to provide the json files for the models; the mod currently lacks the capabilities to automatically generate models with so many variables.
You can copy the vanilla bow model and just swap out the submodel/texture names with the one you need.

**Comment by cramoraint** [comment]
Thanks for that, I seem to have made the bow work correctly. I am now trying with the trident and the channeling enchantment but can't seem to figure out how to make it only affect the item texture and not the held trident model. I am using item/generated for the model parent.

**Comment by Estecka** [comment]
Which version of minecraft are you on exactly ? Changing the trident's held model shouldn't even be possible until MC 1.21.4. If you're on MC 1.21.4, it will work similarly to the bow.

**Comment by cramoraint** [comment]
I am on version 1.21.3, not the texture of it but changing the item sprite is messing with the position of the trident's held model, not too sure why.
![image](https://github.com/user-attachments/assets/5571577b-6e06-4bde-b39f-415dc76df0e8)

**Comment by Estecka** [comment]
Sounds like a bug. I'll look into it.

**Comment by Estecka** [comment]
Should be fixed in [this build](https://github.com/Estecka/mc-Variants-CIT/actions/runs/12038524157). Please let me know if you have any other issue with this.

**Comment by cramoraint** [comment]
Looks to be working correctly from that build, thanks!

![image](https://github.com/user-attachments/assets/330a0026-3361-4f51-a8ec-7b9bd952b920)
