### ISSUE TITLE
[help] Custom Iron Sword texture also changes model in hand (1.21.3)

### ISSUE THREAD

**Issue by heldheld** [Estecka/mc-Enchants-CIT#19]
I made a resource pack that makes a default Iron Sword invisible, only when you give it a custom name 'Iron Sword' or 'Commence Battle', will it show a regular Iron Sword. I managed to make it work, but the problem is that the model of the Iron Sword, when it's in your hands, is also changed and looks like a "regularly held item" instead of how the model of a sword would look. How can I fix this?

![image](https://github.com/user-attachments/assets/47016970-fb8f-4c74-81c5-401dd16b9118)

[Iron Sword resourcepack.zip](https://github.com/user-attachments/files/18048517/Iron.Sword.resourcepack.zip)

**Comment by Estecka** [comment]
Looks like your models use `item/generated` as a parent, you should be using `item/handheld` instead, as the vanilla model does.

**Comment by heldheld** [comment]
> Looks like your models use `item/generated` as a parent, you should be using `item/handheld` instead, as the vanilla model does.

Ahhh yes, I understand now! Fixed it, thank you :)
