### ISSUE TITLE
Could you add a paсk for a custom totem as an example?

### ISSUE THREAD

**Issue by overthinkinn** [Estecka/mc-Enchants-CIT#22]
Just a paсk with a few totems that apply to a specific totem name. For example, "old" = old totem texture, or "dream" = dream skin. I need this so I can make my own paсk with custom totems similar to the example. I would be very grateful.

**Comment by Estecka** [comment]
There's no need for such a specific example. The port of [Even Better Enchant](https://github.com/Estecka/mc-Variants-CIT/releases/download/2.5.0%2B1.21.1/Even.Better.Enchants_Variants-CIT-v2.5.zip) should be good enough an example of a simple setup; there will be little difference between this pack and what you need.
If you have any specific issue that [the documentation](https://github.com/Estecka/mc-Variants-CIT/wiki/Module-Types#custom_name) can't solve, I'd be happy to answer those.
