### ISSUE TITLE
"custom_name" type doesn't seem to be working properly

### ISSUE THREAD

**Issue by wmafranz** [Estecka/mc-Enchants-CIT#8]
I've set up a custom_name typed module with filename "dungeon_keys.json", stored in `assets/minecraft/variants-cit/item/`:
```
{
	"type": "custom_name",
	"modelPrefix": "item/dungeon_keys/"
}
```
I've also set up a minecraft model file in `assets/minecraft/models/item/dungeon_keys/` that is called "decrepit.json" and looks like this:
```
{
	"parent": "minecraft:item/generated",
	"textures": {
		"layer0": "minecraft:item/dungeon_keys/decrepit"
	}
}
```
And it points to a texture file in the `assets/minecraft/textures/item/dungeon_keys/` folder, which has the same name as the last json. 

However, in-game it doesn't seem to work. I can rename a piece of paper "decrepit" in an anvil, and despite the custom_name being just "decrepit", the custom texture doesn't load:
![2024-08-30_11 35 44](https://github.com/user-attachments/assets/90fde808-51c0-45d3-ad47-f6e21c3528ab)

Let me know if I am doing anything wrong or anything like that, otherwise this mod seems to work well!
I have attached the WIP resource pack.
[DonjonKeysCITNOTDONE.zip](https://github.com/user-attachments/files/16819270/DonjonKeysCITNOTDONE.zip)

**Comment by Estecka** [comment]
The module needs to be named `paper.json`, otherwise it doesn't know that it needs to apply to paper.

**Comment by wmafranz** [comment]
Ah I see, this issue you mentioned, combined with my folder being named "variants-cit" as opposed to "variant-cits" were what was preventing it from loading. I do think this should be fixed on the wiki if you don't already plan to, but thank you for helping me fix this!

**Comment by Estecka** [comment]
Wiki has been fixed.
