### ISSUE TITLE
Support for tool with multiple enchantments?

### ISSUE THREAD

**Issue by Jaydee8652** [Estecka/mc-Enchants-CIT#9]
Does this have support for creating tool variants based on enchantments? I assume you could do it with the custom modules but I don't feel like I understand it well enough to even know if what I'm trying to do can be done. Thanks.

**Comment by Estecka** [comment]
Not currently, but that sounds interesting.

How would it behave on a tool with multiple enchantments ? I suppose you'll want one specific enchantment to take priority over the other, and that the enchantments with mutual exclusivity will usually come on top.

**Comment by Jaydee8652** [comment]
I mean depending on how specific you’d end up wanting to be, you’d only really need to look for mutually exclusives. Fortune and Silk on tools, Channelling and Riptide on Tridents etc, you can just assume knowing something has mending and unbreaking isn’t something you need to know visually. It would get harder with swords because you’d probably want to distinguish both the damage type and Fire Aspect though. 

It used to be doable with resewn and I think there are a few packs that do it with Optifine, I was just wondering because this isn’t a direct port wether it was something that has already been figured out.

**Comment by Jaydee8652** [comment]
For now I decided to just use custom names for  a similar effect that the player has to trigger manually.

However I've come across another issue, the custom textures aren't held by the handle in F5. As far as I understand the items in vanilla are tagged somehow as tools and the new variants textures haven't been, is there a way to do that? Thanks

![2024-09-04_14 05 47](https://github.com/user-attachments/assets/3dcfba62-12a0-479e-8f51-d38f59c7189d)

**Comment by Estecka** [comment]
Do you have a link to one of those older packs ? Having something concrete to play around with while coding will help a lot.

Variants based on a single enchantment should be easy enough to do soon.
Since we now have custom enchantments, I won't be hard-coding a list of enchantments to ignore or look for. But it seems feasable to algorithmically pick the most relevants enchantment based on various criterions.

Variance based on a secondary enchantment will definitely take longer. One way I can foresee this becoming possible would be to have a second module that only applies to items with fire aspect, and then provides the variant based on the other enchantment. For that I'd first need to give modules the ability to have restrictions other than the item type.

> However I've come across another issue, the custom textures aren't held by the handle in F5. As far as I understand the items in vanilla are tagged somehow as tools and the new variants textures haven't been, is there a way to do that?

The vanilla models for tools use ~~`item/handlheld`~~ _*`item/handheld`_ instead of `item/generated` as a parent; that's probably what you're missing.

**Comment by Jaydee8652** [comment]
There's quite a few of them, 

Visual Enchantments has a system to display a combination of enchants but I think it was done either manually or procedurally before hand. https://www.curseforge.com/minecraft/texture-packs/visual-enchantments/screenshots

The ones by milesdemillas are where I stole the testing texture from, according to their page it only reads the first two enchantments and does it based on those, so to define what texture you want you need to make the item in an anvil in a certain order. https://www.curseforge.com/members/milesdemillas/projects

**Comment by Jaydee8652** [comment]
> The vanilla models for tools use item/handlheld instead of item/generated as a parent; that's probably what you're missing.

That mostly worked but the textures are now missing, I assume I have to put them somewhere else?
![2024-09-04_14 51 56](https://github.com/user-attachments/assets/71c19759-6289-4bf6-bcd4-1549731db2a2)

Also, I can't get the trident to do anything, I assume this is because it has a 3D model and so works differently. I don't actually want to change the model itself, just the item.

**Comment by Estecka** [comment]
Typo, it was `handheld`, not `handlheld`.

Not sure about the trident. I think its model has a some hardcoded logic in vanilla, but I don't know how that interacts with the mod; might be that the mod's logic is bypassed completely.

**Comment by Jaydee8652** [comment]
![2024-09-04_19 45 49](https://github.com/user-attachments/assets/a65bab5a-b420-4be9-8153-97fbf49b6622)
Its working in game! Thanks so much for the help. I still can't crack tridents though, the JSON file for the icon is identical to everything else in vanilla.

**Comment by Estecka** [comment]
Nothing you can do for now. The trident (and spyglass) have special code that runs after the mod and overrides its changes.

**Comment by Estecka** [comment]
Had a look at those texture packs... and yeah, they are a completely different kind of beast. These feel like they deserve a CIT system of their own.

It should still be technically possible to achieve with the help of multiple modules, like I suggested in the beginning. That just won't be the most optimal way to do it.

**Comment by Estecka** [comment]
> Variance based on a secondary enchantment will definitely take longer. One way I can foresee this becoming possible would be to have a second module that only applies to items with fire aspect, and then provides the variant based on the other enchantment. For that I'd first need to give modules the ability to have restrictions other than the item type.

I couldn't find a good system that would work both globally and for that specific use case, so for now, I've decided to make this an exclusivity of the `enchantment` module.

As planned, you'd have a low priority module that handles CITs with a single enchantments, like before:
```json
{
	"type": "enchantment",
	"priority": 0,
	"items": [ "diamond_sword"],
	"modelPrefix": "item/diamond_sword/", // Fire-aspect-only CIT goes in here
	"modelParent": "item/handheld"
}
```
And then a higher priority module, with a fire_aspect restriction defined in its parameters.
```json
{
	"type": "enchantment",
	"priority": 100,
	"items": [ "diamond_sword"],
	"modelPrefix": "item/fire_aspected_diamond_sword/",
	"modelParent": "item/handheld",
	"parameters": {
		"requiredEnchantments": {
			"fire_aspect": 1
		}
	}
}
```

With this it should also be possible to create CITs that depend on more than 2 enchantments, and require a minimum level for those enchantments.

[Here](https://github.com/Estecka/mc-Variants-CIT/actions/runs/11210932832) is an early build so you can try it out. Please let me know if that works for you before I release it.

**Comment by Jaydee8652** [comment]
Sorry I haven't had the time to properly take a look at it until now,

It all seems to work perfectly!
![Screenshot 2024-10-12 104420](https://github.com/user-attachments/assets/abc2ddd6-5128-4172-a7a5-720627c1891e)

**Comment by Jaydee8652** [comment]
https://drive.google.com/drive/folders/1zmLcTaMoIVk8Ela1uVKS0odgY7ld8WSn?usp=drive_link

Here's the pack in case you wanted to see how I went about it.
